---
title: "'Příkaz catch' se nemůže objevit po \"Finally\" v rámci příkazu \"Try.\""
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 04df7e345120b9373e5d0f4e3205e8b04e3bd000
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 01/23/2019
ms.locfileid: "54669247"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Příkaz catch' se nemůže objevit po "Finally" v rámci příkazu "Try."
A `Catch` příkazu se zobrazí v kódu po `Finally` končící `Try` blok příkazů. `Catch` musí být uvedena v rámci `Try...Catch...Finally` blok příkazů.  
  
 **ID chyby:** BC30379  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
1.  Přesunout `Catch` příkazu vhodnější místo v kódu.  
  
## <a name="see-also"></a>Viz také:
- [Příkaz Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)

