---
title: "'Příkaz catch' se nemůže objevit po \"Finally\" v rámci příkazu \"Try.\""
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 13b8ce225fe487b0c597a6fe81983543e5af535e
ms.sourcegitcommit: 558d78d2a68acd4c95ef23231c8b4e4c7bac3902
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 04/09/2019
ms.locfileid: "59311328"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Příkaz catch' se nemůže objevit po "Finally" v rámci příkazu "Try."
A `Catch` příkazu se zobrazí v kódu po `Finally` končící `Try` blok příkazů. `Catch` musí být uvedena v rámci `Try...Catch...Finally` blok příkazů.  
  
 **ID chyby:** BC30379  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
1. Přesunout `Catch` příkazu vhodnější místo v kódu.  
  
## <a name="see-also"></a>Viz také:

- [Try...Catch....Finally – příkaz](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
