---
title: "'Příkaz catch' se nemůže objevit po \"Finally\" v rámci příkazu \"Try.\""
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 0c0a24190190af28a761c318c3edc5f731424730
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 12/22/2018
ms.locfileid: "53761491"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Příkaz catch' se nemůže objevit po "Finally" v rámci příkazu "Try."
A `Catch` příkazu se zobrazí v kódu po `Finally` končící `Try` blok příkazů. `Catch` musí být uvedena v rámci `Try...Catch...Finally` blok příkazů.  
  
 **ID chyby:** BC30379  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
1.  Přesunout `Catch` příkazu vhodnější místo v kódu.  
  
## <a name="see-also"></a>Viz také  
 [Příkaz Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
