---
title: Výjimky
ms.date: 03/30/2017
ms.assetid: 065205cc-52dd-4f30-9578-b17d8d113136
ms.openlocfilehash: f50e1afa9b1d264a4577bcfe62e939ee669f8ba0
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 01/23/2019
ms.locfileid: "54523971"
---
# <a name="exceptions"></a><span data-ttu-id="aa742-102">Výjimky</span><span class="sxs-lookup"><span data-stu-id="aa742-102">Exceptions</span></span>
<span data-ttu-id="aa742-103">Pracovní postupy můžete použít <xref:System.Activities.Statements.TryCatch> aktivity pro zpracování výjimek, které jsou aktivovány v průběhu provádění pracovního postupu.</span><span class="sxs-lookup"><span data-stu-id="aa742-103">Workflows can use the <xref:System.Activities.Statements.TryCatch> activity to handle exceptions that are raised during the execution of a workflow.</span></span> <span data-ttu-id="aa742-104">Tyto výjimky mohou být zpracovány nebo se může být znovu vyvolány při použití <xref:System.Activities.Statements.Rethrow> aktivity.</span><span class="sxs-lookup"><span data-stu-id="aa742-104">These exceptions can be handled or they can be re-thrown using the <xref:System.Activities.Statements.Rethrow> activity.</span></span> <span data-ttu-id="aa742-105">Aktivity ve službě <xref:System.Activities.Statements.TryCatch.Finally%2A> oddílu jsou spuštěna při buď <xref:System.Activities.Statements.TryCatch.Try%2A> části nebo <xref:System.Activities.Statements.TryCatch.Catches%2A> části dokončí.</span><span class="sxs-lookup"><span data-stu-id="aa742-105">Activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section completes.</span></span> <span data-ttu-id="aa742-106">Hostitelem pracovních postupů <xref:System.Activities.WorkflowApplication> instance můžete použít také <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> obslužnou rutinu události pro zpracování výjimek, které nejsou zpracovány <xref:System.Activities.Statements.TryCatch> aktivity.</span><span class="sxs-lookup"><span data-stu-id="aa742-106">Workflows hosted by a <xref:System.Activities.WorkflowApplication> instance can also use the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> event handler to handle exceptions that are not handled by a <xref:System.Activities.Statements.TryCatch> activity.</span></span>  
  
## <a name="causes-of-exceptions"></a><span data-ttu-id="aa742-107">Příčinami výjimek</span><span class="sxs-lookup"><span data-stu-id="aa742-107">Causes of Exceptions</span></span>  
 <span data-ttu-id="aa742-108">V pracovním postupu mohou být generovány výjimky následujícími způsoby:</span><span class="sxs-lookup"><span data-stu-id="aa742-108">In a workflow, exceptions can be generated in the following ways:</span></span>  
  
-   <span data-ttu-id="aa742-109">Časový limit transakcí v <xref:System.Activities.Statements.TransactionScope>.</span><span class="sxs-lookup"><span data-stu-id="aa742-109">A time-out of transactions in <xref:System.Activities.Statements.TransactionScope>.</span></span>  
  
-   <span data-ttu-id="aa742-110">Explicitní výjimka vyvolaná pomocí pracovního postupu <xref:System.Activities.Statements.Throw> aktivity.</span><span class="sxs-lookup"><span data-stu-id="aa742-110">An explicit exception thrown by the workflow using the <xref:System.Activities.Statements.Throw> activity.</span></span>  
  
-   <span data-ttu-id="aa742-111">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] z aktivity došlo k výjimce.</span><span class="sxs-lookup"><span data-stu-id="aa742-111">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] exception thrown from an activity.</span></span>  
  
-   <span data-ttu-id="aa742-112">Výjimka vyvolaná z externího kódu, jako jsou knihovny, komponenty nebo služby, které se používají v pracovním postupu.</span><span class="sxs-lookup"><span data-stu-id="aa742-112">An exception thrown from external code, such as libraries, components, or services that are used in the workflow.</span></span>  
  
## <a name="handling-exceptions"></a><span data-ttu-id="aa742-113">Zpracování výjimek</span><span class="sxs-lookup"><span data-stu-id="aa742-113">Handling Exceptions</span></span>  
 <span data-ttu-id="aa742-114">Pokud je vyvolána aktivitou a neošetřená výjimka, je výchozí chování k ukončení instance pracovního postupu.</span><span class="sxs-lookup"><span data-stu-id="aa742-114">If an exception is thrown by an activity and is unhandled, the default behavior is to terminate the workflow instance.</span></span> <span data-ttu-id="aa742-115">Pokud vlastní <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> obslužná rutina je k dispozici, jej můžete přepsat toto výchozí chování.</span><span class="sxs-lookup"><span data-stu-id="aa742-115">If a custom <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is present, it can override this default behavior.</span></span> <span data-ttu-id="aa742-116">Tato obslužná rutina poskytuje možnost poskytnout příslušné zpracování, jako jsou vlastní protokolování, přerušení pracovního postupu, zrušení pracovního postupu nebo ukončení pracovního postupu Autor hostitele pracovního postupu.</span><span class="sxs-lookup"><span data-stu-id="aa742-116">This handler gives the workflow host author an opportunity to provide the appropriate handling, such as custom logging, aborting the workflow, canceling the workflow, or terminating the workflow.</span></span>  <span data-ttu-id="aa742-117">Pokud pracovní postup vyvolá výjimku, která není zpracována, <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> je vyvolána obslužná rutina.</span><span class="sxs-lookup"><span data-stu-id="aa742-117">If a workflow raises an exception that is not handled, the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="aa742-118">Existují tři možné akce vrácená <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> který určení konečný výsledek pracovního postupu.</span><span class="sxs-lookup"><span data-stu-id="aa742-118">There are three possible actions returned from <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> which determine the final outcome of the workflow.</span></span>  
  
-   <span data-ttu-id="aa742-119">**Zrušit** – instance pracovního postupu bylo zrušeno je bezproblémové ukončit provádění větve.</span><span class="sxs-lookup"><span data-stu-id="aa742-119">**Cancel** - A cancelled workflow instance is a graceful exit of a branch execution.</span></span> <span data-ttu-id="aa742-120">Zrušení chování lze modelovat (například pomocí aktivity CancellationScope).</span><span class="sxs-lookup"><span data-stu-id="aa742-120">You can model cancelation behavior (for example, by using a CancellationScope activity).</span></span> <span data-ttu-id="aa742-121">Po dokončení procesu zrušení, je vyvolána obslužná rutina dokončeno.</span><span class="sxs-lookup"><span data-stu-id="aa742-121">The Completed handler is invoked when the cancellation process completes.</span></span> <span data-ttu-id="aa742-122">Zrušené pracovní postup je ve stavu zrušeno.</span><span class="sxs-lookup"><span data-stu-id="aa742-122">A cancelled workflow is in the Cancelled state.</span></span>  
  
-   <span data-ttu-id="aa742-123">**Ukončit** – instance ukončení pracovního postupu se nedá obnovit nebo restartovat.</span><span class="sxs-lookup"><span data-stu-id="aa742-123">**Terminate** - A terminated workflow instance cannot be resumed or restarted.</span></span>  <span data-ttu-id="aa742-124">Tím se aktivuje událost dokončení, ve kterém můžete zadat výjimku jako z důvodů, proč byl ukončen.</span><span class="sxs-lookup"><span data-stu-id="aa742-124">This triggers the Completed event in which you can provide an exception as the reason it was terminated.</span></span> <span data-ttu-id="aa742-125">Po dokončení procesu ukončení, je vyvolána obslužná rutina ukončeno.</span><span class="sxs-lookup"><span data-stu-id="aa742-125">The Terminated handler is invoked when the termination process completes.</span></span> <span data-ttu-id="aa742-126">Ukončené pracovní postup je v chybovém stavu.</span><span class="sxs-lookup"><span data-stu-id="aa742-126">A terminated workflow is in the Faulted state.</span></span>  
  
-   <span data-ttu-id="aa742-127">**Přerušit** – instance pracovního postupu byl přerušen lze obnovit pouze v případě, že je nakonfigurovaný jako trvalé.</span><span class="sxs-lookup"><span data-stu-id="aa742-127">**Abort** - An aborted workflow instances can be resumed only if it has been configured to be persistent.</span></span>  <span data-ttu-id="aa742-128">Bez trvalost nelze obnovit pracovního postupu.</span><span class="sxs-lookup"><span data-stu-id="aa742-128">Without persistence, a workflow cannot be resumed.</span></span>  <span data-ttu-id="aa742-129">V okamžiku, pracovní postup byl přerušen, veškeré akce provedené (v paměti) od posledního trvalého bodu budou ztraceny.</span><span class="sxs-lookup"><span data-stu-id="aa742-129">At the point a workflow is aborted, any work done (in memory) since the last persistence point will be lost.</span></span> <span data-ttu-id="aa742-130">Přerušené pracovní postup je vyvolána obslužná rutina přerušeno, pomocí výjimku jako z důvodu po dokončení procesu přerušení.</span><span class="sxs-lookup"><span data-stu-id="aa742-130">For an aborted workflow, the Aborted handler is invoked using the exception as the reason when the abort process completes.</span></span> <span data-ttu-id="aa742-131">Na rozdíl od zrušeno a ukončeno, ale není vyvolána obslužná rutina dokončeno.</span><span class="sxs-lookup"><span data-stu-id="aa742-131">However, unlike Cancelled and Terminated, the Completed handler is not invoked.</span></span> <span data-ttu-id="aa742-132">Přerušené pracovní postup je ve stavu přerušeno.</span><span class="sxs-lookup"><span data-stu-id="aa742-132">An aborted workflow is in an Aborted state.</span></span>  
  
 <span data-ttu-id="aa742-133">Následující příklad vyvolá pracovní postup, který vyvolá výjimku.</span><span class="sxs-lookup"><span data-stu-id="aa742-133">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="aa742-134">Není výjimka ošetřena tímto pracovním postupem a <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> je vyvolána obslužná rutina.</span><span class="sxs-lookup"><span data-stu-id="aa742-134">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="aa742-135"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Jsou kontrolovány k poskytnutí informací o výjimce, a pracovní postup se ukončí.</span><span class="sxs-lookup"><span data-stu-id="aa742-135">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#1](../../../samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#1)]  
  
### <a name="handling-exceptions-with-the-trycatch-activity"></a><span data-ttu-id="aa742-136">Zpracování výjimek s aktivitou TryCatch</span><span class="sxs-lookup"><span data-stu-id="aa742-136">Handling Exceptions with the TryCatch Activity</span></span>  
 <span data-ttu-id="aa742-137">Zpracování výjimek v pracovním postupu pomocí provádí <xref:System.Activities.Statements.TryCatch> aktivity.</span><span class="sxs-lookup"><span data-stu-id="aa742-137">Handling exceptions inside a workflow is performed with the <xref:System.Activities.Statements.TryCatch> activity.</span></span> <span data-ttu-id="aa742-138"><xref:System.Activities.Statements.TryCatch> Má aktivita <xref:System.Activities.Statements.TryCatch.Catches%2A> kolekce <xref:System.Activities.Statements.Catch> aktivity, které jsou spojené s konkrétním <xref:System.Exception> typu.</span><span class="sxs-lookup"><span data-stu-id="aa742-138">The <xref:System.Activities.Statements.TryCatch> activity has a <xref:System.Activities.Statements.TryCatch.Catches%2A> collection of <xref:System.Activities.Statements.Catch> activities that are each associated with a specific <xref:System.Exception> type.</span></span> <span data-ttu-id="aa742-139">Pokud výjimky vyvolané aktivitou, která je součástí <xref:System.Activities.Statements.TryCatch.Try%2A> část <xref:System.Activities.Statements.TryCatch> aktivity shoduje s výjimkou <xref:System.Activities.Statements.Catch%601> aktivity v <xref:System.Activities.Statements.TryCatch.Catches%2A> kolekce a pak výjimka je zpracována.</span><span class="sxs-lookup"><span data-stu-id="aa742-139">If the exception thrown by an activity that is contained in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> activity matches the exception of a <xref:System.Activities.Statements.Catch%601> activity in the <xref:System.Activities.Statements.TryCatch.Catches%2A> collection, then the exception is handled.</span></span> <span data-ttu-id="aa742-140">Pokud je explicitně znovu vyvolána výjimka nebo vyvolána nová výjimka pak tato výjimka předá Nadřazená aktivita.</span><span class="sxs-lookup"><span data-stu-id="aa742-140">If the exception is explicitly re-thrown or a new exception is thrown then this exception passes up to the parent activity.</span></span> <span data-ttu-id="aa742-141">Následující příklad kódu ukazuje <xref:System.Activities.Statements.TryCatch> aktivitu, která zpracovává <xref:System.ApplicationException> , která je vyvolána <xref:System.Activities.Statements.TryCatch.Try%2A> části podle <xref:System.Activities.Statements.Throw> aktivity.</span><span class="sxs-lookup"><span data-stu-id="aa742-141">The following code example shows a <xref:System.Activities.Statements.TryCatch> activity that handles an <xref:System.ApplicationException> that is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section by a <xref:System.Activities.Statements.Throw> activity.</span></span> <span data-ttu-id="aa742-142">Zpráva výjimky je zapsána do konzole <xref:System.Activities.Statements.Catch%601> aktivitu a pak napište zprávu, je zapsán v konzole <xref:System.Activities.Statements.TryCatch.Finally%2A> oddílu.</span><span class="sxs-lookup"><span data-stu-id="aa742-142">The exception's message is written to the console by the <xref:System.Activities.Statements.Catch%601> activity, and then a message is written to the console in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#33](../../../samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#33)]  
  
 <span data-ttu-id="aa742-143">Aktivity v <xref:System.Activities.Statements.TryCatch.Finally%2A> oddílu jsou spuštěna při buď <xref:System.Activities.Statements.TryCatch.Try%2A> části nebo <xref:System.Activities.Statements.TryCatch.Catches%2A> části úspěšně dokončí.</span><span class="sxs-lookup"><span data-stu-id="aa742-143">The activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes.</span></span> <span data-ttu-id="aa742-144"><xref:System.Activities.Statements.TryCatch.Try%2A> Části úspěšně dokončí, pokud nejsou vyvolány žádné výjimky z něj a <xref:System.Activities.Statements.TryCatch.Catches%2A> části úspěšně dokončí, pokud žádné výjimky jsou vyvolány nebo znovu vyvolány z něj.</span><span class="sxs-lookup"><span data-stu-id="aa742-144">The <xref:System.Activities.Statements.TryCatch.Try%2A> section successfully completes if no exceptions are thrown from it, and the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes if no exceptions are thrown or rethrown from it.</span></span> <span data-ttu-id="aa742-145">Pokud dojde k výjimce <xref:System.Activities.Statements.TryCatch.Try%2A> část <xref:System.Activities.Statements.TryCatch> a není buď zpracována <xref:System.Activities.Statements.Catch%601> v <xref:System.Activities.Statements.TryCatch.Catches%2A> části nebo je znovu vyvolána z <xref:System.Activities.Statements.TryCatch.Catches%2A>, aktivity v <xref:System.Activities.Statements.TryCatch.Finally%2A> nebude provedena, pokud dojde k jedné z následujících akcí.</span><span class="sxs-lookup"><span data-stu-id="aa742-145">If an exception is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> and is either not handled by a <xref:System.Activities.Statements.Catch%601> in the <xref:System.Activities.Statements.TryCatch.Catches%2A> section, or is rethrown from the <xref:System.Activities.Statements.TryCatch.Catches%2A>, the activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> will not be executed unless the one of the following occurs.</span></span>  
  
-   <span data-ttu-id="aa742-146">Výjimka je zachycena ve vyšší úrovni <xref:System.Activities.Statements.TryCatch> aktivity v pracovním postupu, bez ohledu na to, zda se je znovu vyvolána z tuto vyšší úroveň <xref:System.Activities.Statements.TryCatch>.</span><span class="sxs-lookup"><span data-stu-id="aa742-146">The exception is caught by a higher level <xref:System.Activities.Statements.TryCatch> activity in the workflow, regardless of whether it is rethrown from that higher level <xref:System.Activities.Statements.TryCatch>.</span></span>  
  
-   <span data-ttu-id="aa742-147">Tato výjimka není ošetřena ve vyšší úrovni <xref:System.Activities.Statements.TryCatch>, řídící kořenového pracovního postupu a pracovní postup nastaven na zrušení namísto ukončit nebo přerušení.</span><span class="sxs-lookup"><span data-stu-id="aa742-147">The exception is not handled by a higher level <xref:System.Activities.Statements.TryCatch>, escapes the root of the workflow, and the workflow is configured to cancel instead of terminate or abort.</span></span> <span data-ttu-id="aa742-148">Pracovní postupy, které jsou hostované pomocí <xref:System.Activities.WorkflowApplication> to můžete nakonfigurovat pomocí manipulace <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> a vrácení <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="aa742-148">Workflows hosted using <xref:System.Activities.WorkflowApplication> can configure this by handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> and returning <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="aa742-149">Příklad zpracování <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> je uvedené dříve v tomto tématu.</span><span class="sxs-lookup"><span data-stu-id="aa742-149">An example of handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> is provided previously in this topic.</span></span> <span data-ttu-id="aa742-150">To služby pracovního postupu můžete nakonfigurovat pomocí <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> uvedete <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="aa742-150">Workflow services can configure this by using <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> and specifying <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="aa742-151">Příklad konfigurace <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, naleznete v tématu [rozšíření hostitele služby pracovního postupu](../../../docs/framework/wcf/feature-details/workflow-service-host-extensibility.md).</span><span class="sxs-lookup"><span data-stu-id="aa742-151">For an example of configuring <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, see [Workflow Service Host Extensibility](../../../docs/framework/wcf/feature-details/workflow-service-host-extensibility.md).</span></span>  
  
## <a name="exception-handling-versus-compensation"></a><span data-ttu-id="aa742-152">Výjimka manipulace a kompenzace</span><span class="sxs-lookup"><span data-stu-id="aa742-152">Exception Handling versus Compensation</span></span>  
 <span data-ttu-id="aa742-153">Rozdíl mezi zpracování výjimek a kompenzace je, že zpracování výjimek dochází při provádění aktivity.</span><span class="sxs-lookup"><span data-stu-id="aa742-153">The difference between exception handling and compensation is that exception handling occurs during the execution of an activity.</span></span> <span data-ttu-id="aa742-154">Kompenzace vyvolá se po úspěšném dokončení aktivity.</span><span class="sxs-lookup"><span data-stu-id="aa742-154">Compensation occurs after an activity has successfully completed.</span></span> <span data-ttu-id="aa742-155">Zpracování výjimek představuje příležitost k vyčištění po aktivita vyvolá výjimku, zatímco poskytuje mechanismus, pomocí kterého lze vrátit zpět úspěšně dokončená práce dříve dokončené aktivity kompenzace.</span><span class="sxs-lookup"><span data-stu-id="aa742-155">Exception handling provides an opportunity to clean up after the activity raises the exception, whereas compensation provides a mechanism by which the successfully completed work of a previously completed activity can be undone.</span></span> <span data-ttu-id="aa742-156">Další informace najdete v tématu [kompenzace](../../../docs/framework/windows-workflow-foundation/compensation.md).</span><span class="sxs-lookup"><span data-stu-id="aa742-156">For more information, see [Compensation](../../../docs/framework/windows-workflow-foundation/compensation.md).</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="aa742-157">Viz také:</span><span class="sxs-lookup"><span data-stu-id="aa742-157">See also</span></span>
- <xref:System.Activities.Statements.TryCatch>
- <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>
- <xref:System.Activities.Statements.CompensableActivity>
