---
title: Použití výjimek - C# Průvodce programováním
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], about exception handling
- exceptions [C#], about exceptions
ms.assetid: 71472c62-320a-470a-97d2-67995180389d
ms.openlocfilehash: 2edaf8c823f228ecb50a256961fe78980826d7f2
ms.sourcegitcommit: 41c0637e894fbcd0713d46d6ef1866f08dc321a2
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 03/01/2019
ms.locfileid: "57203714"
---
# <a name="using-exceptions-c-programming-guide"></a><span data-ttu-id="1876d-102">Použití výjimek (Průvodce programováním v C#)</span><span class="sxs-lookup"><span data-stu-id="1876d-102">Using Exceptions (C# Programming Guide)</span></span>
<span data-ttu-id="1876d-103">V jazyce C# jsou chyby v programu v době běhu šířena přes program pomocí mechanizmu nazývány výjimkami.</span><span class="sxs-lookup"><span data-stu-id="1876d-103">In C#, errors in the program at run time are propagated through the program by using a mechanism called exceptions.</span></span> <span data-ttu-id="1876d-104">Výjimky jsou vyvolaných kódem, který dojde k chybě a zachytit kód, který můžete chybu opravit.</span><span class="sxs-lookup"><span data-stu-id="1876d-104">Exceptions are thrown by code that encounters an error and caught by code that can correct the error.</span></span> <span data-ttu-id="1876d-105">Výjimky mohou být vyvolány pomocí rozhraní .NET Framework common language runtime (CLR) nebo kód v programu.</span><span class="sxs-lookup"><span data-stu-id="1876d-105">Exceptions can be thrown by the .NET Framework common language runtime (CLR) or by code in a program.</span></span> <span data-ttu-id="1876d-106">Jakmile je vyvolána výjimka, rozšíří zásobníkem volání do `catch` se nachází příkaz pro výjimku.</span><span class="sxs-lookup"><span data-stu-id="1876d-106">Once an exception is thrown, it propagates up the call stack until a `catch` statement for the exception is found.</span></span> <span data-ttu-id="1876d-107">Nezachycených výjimek jsou zpracovány rutinou obecná výjimka poskytuje systém, který se zobrazí dialogové okno.</span><span class="sxs-lookup"><span data-stu-id="1876d-107">Uncaught exceptions are handled by a generic exception handler provided by the system that displays a dialog box.</span></span>  
  
 <span data-ttu-id="1876d-108">Výjimky jsou reprezentované pomocí třídy odvozené od <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="1876d-108">Exceptions are represented by classes derived from <xref:System.Exception>.</span></span> <span data-ttu-id="1876d-109">Tato třída identifikuje typ výjimky a obsahuje vlastnosti, které mají podrobnosti o výjimce.</span><span class="sxs-lookup"><span data-stu-id="1876d-109">This class identifies the type of exception and contains properties that have details about the exception.</span></span> <span data-ttu-id="1876d-110">Došlo k výjimce zahrnuje vytvoření instance třídy výjimky odvozené, volitelně konfigurace vlastností výjimky a pak pomocí aktivační objekt `throw` – klíčové slovo.</span><span class="sxs-lookup"><span data-stu-id="1876d-110">Throwing an exception involves creating an instance of an exception-derived class, optionally configuring properties of the exception, and then throwing the object by using the `throw` keyword.</span></span> <span data-ttu-id="1876d-111">Příklad:</span><span class="sxs-lookup"><span data-stu-id="1876d-111">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#1](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#1)]  
  
 <span data-ttu-id="1876d-112">Poté, co je vyvolána výjimka, modul runtime ověří aktuální příkaz Přesvědčte se, zda je v rámci `try` bloku.</span><span class="sxs-lookup"><span data-stu-id="1876d-112">After an exception is thrown, the runtime checks the current statement to see whether it is within a `try` block.</span></span> <span data-ttu-id="1876d-113">Pokud se jedná, některé `catch` bloky přidružené `try` bloku se zkontroluje, zda lze zachytit výjimku.</span><span class="sxs-lookup"><span data-stu-id="1876d-113">If it is, any `catch` blocks associated with the `try` block are checked to see whether they can catch the exception.</span></span> <span data-ttu-id="1876d-114">`Catch` bloky obvykle určují typy výjimek; Pokud typ `catch` blok je stejného typu jako výjimky nebo základní třídu výjimky, `catch` bloku může zpracovat metodu.</span><span class="sxs-lookup"><span data-stu-id="1876d-114">`Catch` blocks typically specify exception types; if the type of the `catch` block is the same type as the exception, or a base class of the exception, the `catch` block can handle the method.</span></span> <span data-ttu-id="1876d-115">Příklad:</span><span class="sxs-lookup"><span data-stu-id="1876d-115">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#2](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#2)]  
  
 <span data-ttu-id="1876d-116">Pokud příkaz, který vyvolá výjimku, není v rozsahu `try` bloku nebo, pokud `try` blok, který ji obklopuje nemá odpovídající `catch` bloku, modul runtime kontroluje volání metody pro `try` příkazu a `catch` bloky.</span><span class="sxs-lookup"><span data-stu-id="1876d-116">If the statement that throws an exception is not within a `try` block or if the `try` block that encloses it has no matching `catch` block, the runtime checks the calling method for a `try` statement and `catch` blocks.</span></span> <span data-ttu-id="1876d-117">Modul runtime bude pokračovat až do volání zásobníku, vyhledávání kompatibilní `catch` bloku.</span><span class="sxs-lookup"><span data-stu-id="1876d-117">The runtime continues up the calling stack, searching for a compatible `catch` block.</span></span> <span data-ttu-id="1876d-118">Po `catch` bloku je nalezen a spuštěn, řízení je předáno další příkaz, po který `catch` bloku.</span><span class="sxs-lookup"><span data-stu-id="1876d-118">After the `catch` block is found and executed, control is passed to the next statement after that `catch` block.</span></span>  
  
 <span data-ttu-id="1876d-119">A `try` příkaz může obsahovat více než jednu `catch` bloku.</span><span class="sxs-lookup"><span data-stu-id="1876d-119">A `try` statement can contain more than one `catch` block.</span></span> <span data-ttu-id="1876d-120">První `catch` je proveden příkaz, který dokáže zpracovat výjimky; všechny následující `catch` příkazy, i v případě, že jsou kompatibilní, jsou ignorovány.</span><span class="sxs-lookup"><span data-stu-id="1876d-120">The first `catch` statement that can handle the exception is executed; any following `catch` statements, even if they are compatible, are ignored.</span></span> <span data-ttu-id="1876d-121">Proto catch bloky by měla být vždy seřazené od nejvíce konkrétní (nebo nejvíce odvozenému) nejméně specifická.</span><span class="sxs-lookup"><span data-stu-id="1876d-121">Therefore, catch blocks should always be ordered from most specific (or most-derived) to least specific.</span></span> <span data-ttu-id="1876d-122">Příklad:</span><span class="sxs-lookup"><span data-stu-id="1876d-122">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#3](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#3)]  
  
 <span data-ttu-id="1876d-123">Před `catch` blok je spuštěn, modul runtime kontroluje `finally` bloky.</span><span class="sxs-lookup"><span data-stu-id="1876d-123">Before the `catch` block is executed, the runtime checks for `finally` blocks.</span></span> <span data-ttu-id="1876d-124">`Finally` bloky povolit programátorovi, aby vyčistit všechny nejednoznačný stav, který by mohl být přetrvávající ze přerušené `try` bloku nebo uvolnit všem externím prostředkům (například obslužné rutiny grafiky, připojení k databázi nebo datové proudy souborů) bez čekání uvolňování paměti kolekce v modulu runtime pro dokončení objekty.</span><span class="sxs-lookup"><span data-stu-id="1876d-124">`Finally` blocks enable the programmer to clean up any ambiguous state that could be left over from an aborted `try` block, or to release any external resources (such as graphics handles, database connections or file streams) without waiting for the garbage collector in the runtime to finalize the objects.</span></span> <span data-ttu-id="1876d-125">Příklad:</span><span class="sxs-lookup"><span data-stu-id="1876d-125">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#4](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#4)]  
  
 <span data-ttu-id="1876d-126">Pokud `WriteByte()` došlo k výjimce, kód ve druhé `try` blok, který se pokusí znovu otevřete soubor selže, pokud `file.Close()` není volána, a soubor zůstane uzamčen.</span><span class="sxs-lookup"><span data-stu-id="1876d-126">If `WriteByte()` threw an exception, the code in the second `try` block that tries to reopen the file would fail if `file.Close()` is not called, and the file would remain locked.</span></span> <span data-ttu-id="1876d-127">Protože `finally` bloky provádějí i v případě, že je vyvolána výjimka, `finally` blok v předchozím příkladu povolí pro soubor, který má být správně uzavřena, a pomáhá zabránit chybu.</span><span class="sxs-lookup"><span data-stu-id="1876d-127">Because `finally` blocks are executed even if an exception is thrown, the `finally` block in the previous example allows for the file to be closed correctly and helps avoid an error.</span></span>  
  
 <span data-ttu-id="1876d-128">Pokud žádné kompatibilní `catch` bloku se nachází v zásobníku volání po dojde k výjimce, nenastane některá z tři věci:</span><span class="sxs-lookup"><span data-stu-id="1876d-128">If no compatible `catch` block is found on the call stack after an exception is thrown, one of three things occurs:</span></span>  
  
-   <span data-ttu-id="1876d-129">Je-li výjimka v rámci finalizační metodu, finalizační metoda byla přerušena a základní finalizační metodu, pokud existuje, je volána.</span><span class="sxs-lookup"><span data-stu-id="1876d-129">If the exception is within a finalizer, the finalizer is aborted and the base finalizer, if any, is called.</span></span>  
  
-   <span data-ttu-id="1876d-130">Pokud obsahuje zásobník volání statického konstruktoru nebo inicializátoru statické pole <xref:System.TypeInitializationException> je vyvolána výjimka s původní výjimky přiřazené <xref:System.Exception.InnerException%2A> vlastnost novou výjimku.</span><span class="sxs-lookup"><span data-stu-id="1876d-130">If the call stack contains a static constructor, or a static field initializer, a <xref:System.TypeInitializationException> is thrown, with the original exception assigned to the <xref:System.Exception.InnerException%2A> property of the new exception.</span></span>  
  
-   <span data-ttu-id="1876d-131">Pokud je dosaženo začátku vlákno, vlákno ukončeno.</span><span class="sxs-lookup"><span data-stu-id="1876d-131">If the start of the thread is reached, the thread is terminated.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="1876d-132">Viz také:</span><span class="sxs-lookup"><span data-stu-id="1876d-132">See also</span></span>

- [<span data-ttu-id="1876d-133">Průvodce programováním v jazyce C#</span><span class="sxs-lookup"><span data-stu-id="1876d-133">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)
- [<span data-ttu-id="1876d-134">Výjimky a jejich zpracování</span><span class="sxs-lookup"><span data-stu-id="1876d-134">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)
