---
title: Použití výjimek – C# Průvodce programováním
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], about exception handling
- exceptions [C#], about exceptions
ms.assetid: 71472c62-320a-470a-97d2-67995180389d
ms.openlocfilehash: 8d0fe4b8c2ba3e64aa7ee34fc9d02b29bda5c017
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 08/19/2019
ms.locfileid: "69590166"
---
# <a name="using-exceptions-c-programming-guide"></a><span data-ttu-id="a056c-102">Použití výjimek (Průvodce programováním v C#)</span><span class="sxs-lookup"><span data-stu-id="a056c-102">Using Exceptions (C# Programming Guide)</span></span>
<span data-ttu-id="a056c-103">V C#systému jsou chyby v programu v době běhu šířeny prostřednictvím programu pomocí mechanismu nazývaného výjimky.</span><span class="sxs-lookup"><span data-stu-id="a056c-103">In C#, errors in the program at run time are propagated through the program by using a mechanism called exceptions.</span></span> <span data-ttu-id="a056c-104">Výjimky jsou vyvolány kódem, který zaznamená chybu a zachycena kódem, který může chybu opravit.</span><span class="sxs-lookup"><span data-stu-id="a056c-104">Exceptions are thrown by code that encounters an error and caught by code that can correct the error.</span></span> <span data-ttu-id="a056c-105">Výjimky mohou být vyvolány .NET Framework Common Language Runtime (CLR) nebo pomocí kódu v programu.</span><span class="sxs-lookup"><span data-stu-id="a056c-105">Exceptions can be thrown by the .NET Framework common language runtime (CLR) or by code in a program.</span></span> <span data-ttu-id="a056c-106">Jakmile je vyvolána výjimka, rozšíří zásobník volání, dokud `catch` nebude nalezen příkaz pro výjimku.</span><span class="sxs-lookup"><span data-stu-id="a056c-106">Once an exception is thrown, it propagates up the call stack until a `catch` statement for the exception is found.</span></span> <span data-ttu-id="a056c-107">Nezachycené výjimky jsou zpracovávány pomocí obecné obslužné rutiny výjimky poskytované systémem, který zobrazuje dialogové okno.</span><span class="sxs-lookup"><span data-stu-id="a056c-107">Uncaught exceptions are handled by a generic exception handler provided by the system that displays a dialog box.</span></span>  
  
 <span data-ttu-id="a056c-108">Výjimky jsou reprezentovány třídami <xref:System.Exception>odvozenými z.</span><span class="sxs-lookup"><span data-stu-id="a056c-108">Exceptions are represented by classes derived from <xref:System.Exception>.</span></span> <span data-ttu-id="a056c-109">Tato třída identifikuje typ výjimky a obsahuje vlastnosti, které obsahují podrobnosti o výjimce.</span><span class="sxs-lookup"><span data-stu-id="a056c-109">This class identifies the type of exception and contains properties that have details about the exception.</span></span> <span data-ttu-id="a056c-110">Vyvolání výjimky zahrnuje vytvoření instance třídy odvozené od výjimky, volitelně konfiguraci vlastností výjimky a následné vyvolání objektu pomocí `throw` klíčového slova.</span><span class="sxs-lookup"><span data-stu-id="a056c-110">Throwing an exception involves creating an instance of an exception-derived class, optionally configuring properties of the exception, and then throwing the object by using the `throw` keyword.</span></span> <span data-ttu-id="a056c-111">Příklad:</span><span class="sxs-lookup"><span data-stu-id="a056c-111">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#1](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#1)]  
  
 <span data-ttu-id="a056c-112">Po vyvolání výjimky modul runtime zkontroluje aktuální příkaz a zjistí, zda je v rámci `try` bloku.</span><span class="sxs-lookup"><span data-stu-id="a056c-112">After an exception is thrown, the runtime checks the current statement to see whether it is within a `try` block.</span></span> <span data-ttu-id="a056c-113">Pokud je, jsou zkontrolovány všechny `catch` bloky přidružené `try` k bloku, aby bylo vidět, zda mohou zachytit výjimku.</span><span class="sxs-lookup"><span data-stu-id="a056c-113">If it is, any `catch` blocks associated with the `try` block are checked to see whether they can catch the exception.</span></span> <span data-ttu-id="a056c-114">`Catch`bloky obvykle určují typy výjimek; Pokud je typ `catch` bloku shodný s typem výjimky nebo základní třídou výjimky `catch` , může blok zpracovat metodu.</span><span class="sxs-lookup"><span data-stu-id="a056c-114">`Catch` blocks typically specify exception types; if the type of the `catch` block is the same type as the exception, or a base class of the exception, the `catch` block can handle the method.</span></span> <span data-ttu-id="a056c-115">Příklad:</span><span class="sxs-lookup"><span data-stu-id="a056c-115">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#2](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#2)]  
  
 <span data-ttu-id="a056c-116">Pokud příkaz, který vyvolá `try` výjimku, není uvnitř bloku nebo `try` Pokud blok, který ho obklopuje, nemá odpovídající `catch` blok, modul runtime zkontroluje volající metodu pro `try` příkaz a `catch` bloky.</span><span class="sxs-lookup"><span data-stu-id="a056c-116">If the statement that throws an exception is not within a `try` block or if the `try` block that encloses it has no matching `catch` block, the runtime checks the calling method for a `try` statement and `catch` blocks.</span></span> <span data-ttu-id="a056c-117">Modul runtime pokračuje v zásobníku volání a hledá kompatibilní `catch` blok.</span><span class="sxs-lookup"><span data-stu-id="a056c-117">The runtime continues up the calling stack, searching for a compatible `catch` block.</span></span> <span data-ttu-id="a056c-118">Po nalezení a provedení `catch` blokujeovládacíprvekpředándalšímupříkazupotomtobloku.`catch`</span><span class="sxs-lookup"><span data-stu-id="a056c-118">After the `catch` block is found and executed, control is passed to the next statement after that `catch` block.</span></span>  
  
 <span data-ttu-id="a056c-119">Příkaz může obsahovat více než jeden `catch` blok. `try`</span><span class="sxs-lookup"><span data-stu-id="a056c-119">A `try` statement can contain more than one `catch` block.</span></span> <span data-ttu-id="a056c-120">Je proveden `catch` první příkaz, který může zpracovat výjimku; všechny následující `catch` příkazy, i když jsou kompatibilní, jsou ignorovány.</span><span class="sxs-lookup"><span data-stu-id="a056c-120">The first `catch` statement that can handle the exception is executed; any following `catch` statements, even if they are compatible, are ignored.</span></span> <span data-ttu-id="a056c-121">Proto by bloky catch měly být vždy řazeny z nejvíce specifického (nebo nejvíce odvozeného) na nejméně konkrétní.</span><span class="sxs-lookup"><span data-stu-id="a056c-121">Therefore, catch blocks should always be ordered from most specific (or most-derived) to least specific.</span></span> <span data-ttu-id="a056c-122">Příklad:</span><span class="sxs-lookup"><span data-stu-id="a056c-122">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#3](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#3)]  
  
 <span data-ttu-id="a056c-123">Před provedením `finally` bloku modul runtime vyhledá bloky. `catch`</span><span class="sxs-lookup"><span data-stu-id="a056c-123">Before the `catch` block is executed, the runtime checks for `finally` blocks.</span></span> <span data-ttu-id="a056c-124">`Finally`bloky umožňují programátorovi vyčistit libovolný dvojznačný stav, který by mohl zůstat z přerušeného `try` bloku, nebo uvolnit jakékoli externí prostředky (jako jsou grafické popisovače, databázová připojení nebo datové proudy souborů) bez čekání na uvolnění paměti. kolektor v modulu runtime pro finalizaci objektů.</span><span class="sxs-lookup"><span data-stu-id="a056c-124">`Finally` blocks enable the programmer to clean up any ambiguous state that could be left over from an aborted `try` block, or to release any external resources (such as graphics handles, database connections or file streams) without waiting for the garbage collector in the runtime to finalize the objects.</span></span> <span data-ttu-id="a056c-125">Příklad:</span><span class="sxs-lookup"><span data-stu-id="a056c-125">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#4](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#4)]  
  
 <span data-ttu-id="a056c-126">Pokud `WriteByte()` vyvolal výjimku, kód v druhém `try` bloku, který se pokusí znovu otevřít soubor, selže, pokud `file.Close()` není volán, a soubor by zůstal uzamčen.</span><span class="sxs-lookup"><span data-stu-id="a056c-126">If `WriteByte()` threw an exception, the code in the second `try` block that tries to reopen the file would fail if `file.Close()` is not called, and the file would remain locked.</span></span> <span data-ttu-id="a056c-127">Vzhledem `finally` k tomu, že jsou bloky spouštěny i v případě `finally` , že dojde k výjimce, blok v předchozím příkladu umožňuje, aby se soubor správně zavřel, a pomáhá vyhnout se chybě.</span><span class="sxs-lookup"><span data-stu-id="a056c-127">Because `finally` blocks are executed even if an exception is thrown, the `finally` block in the previous example allows for the file to be closed correctly and helps avoid an error.</span></span>  
  
 <span data-ttu-id="a056c-128">Pokud v zásobníku `catch` volání není po vyvolání výjimky nalezen žádný kompatibilní blok, nastane jedna ze tří akcí:</span><span class="sxs-lookup"><span data-stu-id="a056c-128">If no compatible `catch` block is found on the call stack after an exception is thrown, one of three things occurs:</span></span>  
  
- <span data-ttu-id="a056c-129">Pokud je výjimka v finalizační metodě, finalizační metoda je přerušena a základní finalizační metoda, pokud existuje, je volána.</span><span class="sxs-lookup"><span data-stu-id="a056c-129">If the exception is within a finalizer, the finalizer is aborted and the base finalizer, if any, is called.</span></span>  
  
- <span data-ttu-id="a056c-130">Pokud zásobník volání obsahuje statický konstruktor nebo inicializátor statických polí, <xref:System.TypeInitializationException> je vyvolána, s původní výjimkou přiřazenou <xref:System.Exception.InnerException%2A> vlastnosti nové výjimky.</span><span class="sxs-lookup"><span data-stu-id="a056c-130">If the call stack contains a static constructor, or a static field initializer, a <xref:System.TypeInitializationException> is thrown, with the original exception assigned to the <xref:System.Exception.InnerException%2A> property of the new exception.</span></span>  
  
- <span data-ttu-id="a056c-131">Pokud je dosaženo začátku vlákna, vlákno je ukončeno.</span><span class="sxs-lookup"><span data-stu-id="a056c-131">If the start of the thread is reached, the thread is terminated.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="a056c-132">Viz také:</span><span class="sxs-lookup"><span data-stu-id="a056c-132">See also</span></span>

- [<span data-ttu-id="a056c-133">Průvodce programováním v jazyce C#</span><span class="sxs-lookup"><span data-stu-id="a056c-133">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="a056c-134">Výjimky a jejich zpracování</span><span class="sxs-lookup"><span data-stu-id="a056c-134">Exceptions and Exception Handling</span></span>](./index.md)
