---
ms.openlocfilehash: ab2907b05bff409fed9a370d5cbebbf3d1575d2f
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: HT
ms.contentlocale: cs-CZ
ms.lasthandoff: 04/22/2019
ms.locfileid: "59981544"
---
### <a name="systemthreadingtaskstask-no-longer-throw-objectdisposedexception-after-object-is-disposed"></a><span data-ttu-id="7bd33-101">System.Threading.Tasks.Task již nezobrazují výjimku objectdisposedexception – po uvolnění objektu</span><span class="sxs-lookup"><span data-stu-id="7bd33-101">System.Threading.Tasks.Task no longer throw ObjectDisposedException after object is disposed</span></span>

|   |   |
|---|---|
|<span data-ttu-id="7bd33-102">Podrobnosti</span><span class="sxs-lookup"><span data-stu-id="7bd33-102">Details</span></span>|<span data-ttu-id="7bd33-103">S výjimkou <xref:System.Threading.Tasks.Task.System%23IAsyncResult%23AsyncWaitHandle>, <xref:System.Threading.Tasks.Task?displayProperty=name> metody již nezobrazují výjimku <xref:System.ObjectDisposedException?displayProperty=name> po vyřazení objektu. Tato změna podporuje používání úkolů v mezipaměti.</span><span class="sxs-lookup"><span data-stu-id="7bd33-103">Except for <xref:System.Threading.Tasks.Task.System%23IAsyncResult%23AsyncWaitHandle>, <xref:System.Threading.Tasks.Task?displayProperty=name> methods no longer throw an <xref:System.ObjectDisposedException?displayProperty=name> exception after the object is disposed.This change supports the use of cached tasks.</span></span> <span data-ttu-id="7bd33-104">Například metoda může vrátit úlohu uloženou v mezipaměti pro zastupování již dokončené operace namísto přidělení nové úlohy.</span><span class="sxs-lookup"><span data-stu-id="7bd33-104">For example, a method can return a cached task to represent an already completed operation instead of allocating a new task.</span></span> <span data-ttu-id="7bd33-105">To nebylo v předchozích verzích rozhraní .NET Framework možné, protože příjemci úlohy s ní mohli nakládat.</span><span class="sxs-lookup"><span data-stu-id="7bd33-105">This was impossible in previous .NET Framework versions, because any consumer of the task could dispose of it, which rendered it unusable.</span></span>|
|<span data-ttu-id="7bd33-106">Doporučení</span><span class="sxs-lookup"><span data-stu-id="7bd33-106">Suggestion</span></span>|<span data-ttu-id="7bd33-107">Mějte na paměti, že metody úloh může již nezobrazují výjimku <xref:System.ObjectDisposedException?displayProperty=name> v případech, kdy vyřazení objektu.</span><span class="sxs-lookup"><span data-stu-id="7bd33-107">Be aware that Task methods may no longer throw <xref:System.ObjectDisposedException?displayProperty=name> in cases when the object is disposed.</span></span> <span data-ttu-id="7bd33-108">Pokud aplikace se v závislosti na tuto výjimku vědět, že byl odstraněn úkolu, musí aktualizovat na hodnotu explicitně kontrolovat stav úlohy pomocí <xref:System.Threading.Tasks.Task.Status>.</span><span class="sxs-lookup"><span data-stu-id="7bd33-108">If an app was depending on this exception to know that a task was disposed, it should be updated to explicitly check the task's status using <xref:System.Threading.Tasks.Task.Status>.</span></span>|
|<span data-ttu-id="7bd33-109">Rozsah</span><span class="sxs-lookup"><span data-stu-id="7bd33-109">Scope</span></span>|<span data-ttu-id="7bd33-110">Vedlejší</span><span class="sxs-lookup"><span data-stu-id="7bd33-110">Minor</span></span>|
|<span data-ttu-id="7bd33-111">Version</span><span class="sxs-lookup"><span data-stu-id="7bd33-111">Version</span></span>|<span data-ttu-id="7bd33-112">4.5</span><span class="sxs-lookup"><span data-stu-id="7bd33-112">4.5</span></span>|
|<span data-ttu-id="7bd33-113">Type</span><span class="sxs-lookup"><span data-stu-id="7bd33-113">Type</span></span>|<span data-ttu-id="7bd33-114">Modul runtime</span><span class="sxs-lookup"><span data-stu-id="7bd33-114">Runtime</span></span>|
